namespace Solutions
{
    public class Problem2
    {
        /*
         * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
         * By starting with 1 and 2, the first 10 terms will be:
         *      
         *      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
         * 
         * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
         */
        public static void Solution()
        {

            int limit = 4000000;
            int result = 2;
            int prev1 = 1;
            int prev2 = 2;

            while (prev1 + prev2 <= limit)
            {
                int total = prev1 + prev2;
                if (total % 2 == 0)
                    result += total;

                int temp = prev1;
                prev1 = prev2;
                prev2 += temp;
            }

            Console.WriteLine("result: " + result);
        }
    }
}
